version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: visitor-analytics-api-app
    container_name: visitor-analytics-api-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - mysql
      - redis
    networks:
      - visitor-analytics-network

  nginx:
    image: nginx:latest
    container_name: visitor-analytics-api-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - visitor-analytics-network

  mysql:
    image: mysql:8.0
    container_name: visitor-analytics-api-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel_db
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - visitor-analytics-network

  redis:
    image: redis:latest
    container_name: visitor-analytics-api-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - visitor-analytics-network

volumes:
  db_data:

networks:
  visitor-analytics-network:
    driver: bridge
